voxel_length: 0.001
sdf_trunc: 0.004
depth_min: 0.1
depth_max: 1.5
depth_quantile_low: 0.0
depth_quantile_high: 1.0
use_mask: true
min_component_triangles: 250
min_component_ratio: 0.01
collision_target_triangles: 5000
min_valid_depth_ratio: 0.01
